site_name: GradsFlow
site_description: "An open-source AutoML Library based on PyTorch"
site_author: Aniket Maurya
copyright: 'Copyright &copy; 2021 GradsFlow'

banner_url: https://ik.imagekit.io/gradsflow/logo/v2/gf-logo-geadsflow-orange-white-bg_y5v0LNPvdeM.png
repo_url: https://github.com/gradsflow/gradsflow/
repo_name: gradsflow/gradsflow

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  logo: https://ik.imagekit.io/gradsflow/logo/v2/gf-logo-gflow-black_9ZE8jOuKXTm.svg?updatedAt=1633488021249
  favicon: https://ik.imagekit.io/gradsflow/logo/v2/gf-logo-gflow-white_vCxfpINvg.svg
  features:
    - search.suggest
    - search.highlight

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized
  - search
  - autorefs
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false

extra:
  homepage: https://docs.gradsflow.com

nav:
  - Intro: 'index.md'
  - Examples:
      - Auto Image Classification: 'examples/nbs/01-ImageClassification.ipynb'
      - Auto Text Classification: 'examples/nbs/02-TextClassification.ipynb'
      - Auto Summarization: 'examples/nbs/03-TextSummarization.ipynb'
      - Remote Dataset Loading: 'examples/nbs/04-RayDataset.ipynb'
      - Model Training: 'examples/nbs/05-model_fit.ipynb'
      - AutoModel - HyperParameter Search: 'examples/nbs/06-AutoModel_fit.ipynb'
      - Pix2Pix GAN Code Explanation: 'examples/nbs/Pix2Pix_explained_with_code.ipynb'
      - ðŸ¤— HuggingFace Training Example: 'examples/nbs/2021-10-3-huggingface-training.ipynb'
  - API References:
      - Core: gradsflow/core
      - Model:
        - gradsflow/models/base.md
        - gradsflow/models/model.md
        - gradsflow/models/tracker.md
      - Tuner: gradsflow/tuner
      - AutoTasks: gradsflow/tasks
      - Data: gradsflow/data
      - utility: gradsflow/utility.md
  - Release Notes: 'CHANGELOG.md'
